Repository ExpediaGroup/github-helpers, pull requests merged in 2021-12, with the labels that each got.

#29 feat: support CODEOWNERS in pr approval helpers
  .eslintrc.json
  .github/CODEOWNERS
  .github/workflows/add-pr-approval-label.yml
  .github/workflows/assign-pr-reviewers.yml
  dist/154.index.js
  dist/154.index.js.map
  dist/263.index.js
  dist/263.index.js.map
  dist/445.index.js
  dist/445.index.js.map
  dist/533.index.js
  dist/533.index.js.map
  dist/905.index.js
  dist/905.index.js.map
  dist/913.index.js
  dist/913.index.js.map
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
  src/helpers/add-pr-approval-label.ts
  src/helpers/assign-pr-reviewers.ts
  src/helpers/generate-path-matrix.ts
  src/helpers/get-changed-files.ts
  src/helpers/move-project-card.ts
  src/utils/get-changed-filepaths.ts
  src/utils/get-core-member-logins.ts
  test/helpers/add-pr-approval-label.test.ts
  test/helpers/assign-pr-reviewers.test.ts
  test/utils/get-core-member-logins.test.ts
Labels: PEER APPROVED, CORE APPROVED

#33 feat(filter-paths): add `glob` input to filter-paths to allow filtering by glob instead of substr
  action.yml
  dist/118.index.js
  dist/118.index.js.map
  dist/136.index.js
  dist/136.index.js.map
  dist/228.index.js
  dist/228.index.js.map
  dist/438.index.js
  dist/438.index.js.map
  dist/445.index.js
  dist/445.index.js.map
  dist/545.index.js
  dist/545.index.js.map
  dist/680.index.js
  dist/680.index.js.map
  dist/747.index.js
  dist/747.index.js.map
  dist/794.index.js
  dist/794.index.js.map
  dist/940.index.js
  dist/940.index.js.map
  dist/action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
  src/helpers/filter-paths.ts
  test/helpers/filter-paths.test.ts
Labels: CORE APPROVED

#35 docs: use `ExpediaGroup` as namespace instead of `actions`
  README.md
Labels: CORE APPROVED

#34 fix: check-pr-title regex to include "BREAKING CHANGE" and add to PR checks
  dist/0.index.js
  dist/0.index.js.map
  dist/101.index.js
  dist/101.index.js.map
  dist/4.index.js
  dist/4.index.js.map
  dist/420.index.js
  dist/420.index.js.map
  dist/807.index.js
  dist/807.index.js.map
  dist/905.index.js
  dist/905.index.js.map
  dist/956.index.js
  dist/956.index.js.map
  src/constants.ts
Labels: CORE APPROVED

#37 fix: attach headers to project card helpers
  dist/124.index.js
  dist/124.index.js.map
  dist/263.index.js
  dist/263.index.js.map
  src/helpers/create-project-card.ts
  src/helpers/move-project-card.ts
  src/types.d.ts
  test/helpers/create-project-card.test.ts
  test/helpers/move-project-card.test.ts
Labels: PEER APPROVED

#46 fix: remove ready for merge label on pr merge
  dist/473.index.js
  dist/473.index.js.map
  src/helpers/manage-merge-queue.ts
  test/helpers/manage-merge-queue.test.ts
Labels: QUEUED FOR MERGE #1, READY FOR MERGE

#47 fix: query for queued prs after removing from queue
  dist/473.index.js
  dist/473.index.js.map
  dist/61.index.js
  dist/61.index.js.map
  src/helpers/manage-merge-queue.ts
  src/helpers/remove-label.ts
  src/utils/update-merge-queue.ts
  test/helpers/manage-merge-queue.test.ts
  test/utils/update-merge-queue.test.ts
Labels: QUEUED FOR MERGE #1, READY FOR MERGE

#48 fix: set commit status when pr is first in queue
  dist/0.index.js
  dist/0.index.js.map
  dist/101.index.js
  dist/101.index.js.map
  dist/124.index.js
  dist/124.index.js.map
  dist/263.index.js
  dist/263.index.js.map
  dist/4.index.js
  dist/4.index.js.map
  dist/420.index.js
  dist/420.index.js.map
  dist/473.index.js
  dist/473.index.js.map
  dist/807.index.js
  dist/807.index.js.map
  dist/905.index.js
  dist/905.index.js.map
  dist/956.index.js
  dist/956.index.js.map
  src/constants.ts
  src/helpers/manage-merge-queue.ts
  src/utils/update-merge-queue.ts
  test/helpers/manage-merge-queue.test.ts
  test/utils/update-merge-queue.test.ts
Labels: QUEUED FOR MERGE #1, READY FOR MERGE

#45 refactor: approve pr helper
  .github/workflows/approve-pr.yml
  README.md
  action.yml
  dist/522.index.js
  dist/522.index.js.map
  dist/action.yml
  dist/index.js
  dist/index.js.map
  src/helpers/approve-pr.ts
  test/helpers/approve-pr.test.ts
Labels: CORE APPROVED, QUEUED FOR MERGE #1, READY FOR MERGE
