Repository ExpediaGroup/github-helpers, pull requests merged in 2022-03, with the labels that each got.

#139 feat(generate-path-matrix): allow globs to be used instead of paths
  dist/533.index.js
  dist/533.index.js.map
  package-lock.json
  src/helpers/generate-path-matrix.ts
  test/helpers/generate-path-matrix.test.ts
Labels: CORE APPROVED

#147 fix(manage-merge-queue): improve reliability of open pr search
  dist/4.index.js.map
  dist/473.index.js
  dist/473.index.js.map
  src/helpers/manage-merge-queue.ts
  src/helpers/prepare-queued-pr-for-merge.ts
  src/types.d.ts
  src/utils/update-merge-queue.ts
  test/helpers/manage-merge-queue.test.ts
  test/utils/update-merge-queue.test.ts
Labels: CORE APPROVED, QUEUED FOR MERGE #1, READY FOR MERGE

#150 fix(manage-merge-queue): sort prs by updated
  .github/workflows/manage-merge-queue.yml
  dist/473.index.js
  dist/473.index.js.map
  src/helpers/manage-merge-queue.ts
Labels: QUEUED FOR MERGE #1, READY FOR MERGE

#159 feat: rerun-pr-checks
  .github/workflows/rerun-pr-checks.yml
  README.md
  dist/766.index.js
  dist/766.index.js.map
  dist/832.index.js
  dist/832.index.js.map
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/helpers/rerun-pr-checks.ts
  test/helpers/rerun-pr-checks.test.ts
Labels: CORE APPROVED

#167 chore: add debug statement to error handler when updating branch in pr queue
  dist/4.index.js
  dist/4.index.js.map
  dist/473.index.js
  dist/473.index.js.map
  src/helpers/prepare-queued-pr-for-merge.ts
  test/helpers/prepare-queued-pr-for-merge.test.ts
Labels: CORE APPROVED

#156 feat: allow manage-merge-queue to paginate all PRs
  dist/473.index.js
  dist/473.index.js.map
  src/helpers/manage-merge-queue.ts
  test/helpers/manage-merge-queue.test.ts
Labels: CORE APPROVED

#171 fix: use rerun_url in rerun-pr-checks to ensure base url is correct
  dist/766.index.js
  dist/766.index.js.map
  src/helpers/rerun-pr-checks.ts
  test/helpers/rerun-pr-checks.test.ts
Labels: CORE APPROVED

#172 chore: remove redundant error handling in rerun-pr-checks
  dist/766.index.js
  dist/766.index.js.map
  src/helpers/rerun-pr-checks.ts
Labels: CORE APPROVED
